<div id="uq-footer">
  <div id="uq-footer-inner" class="container default-width">

    <div class="row">
      <div class="mobile-four nine columns">
        <h6>© The University of Queensland</h6>
        <ul>
          <li class="uq-enquiries">Enquiries: <a href="tel:+6173365111">+61 7 3365 1111</a></li>
          <li class="uq-contacts"><a href="http://uq.edu.au/contacts">UQ Contacts</a></li>
          <li class="uq-abn secondary"><abbr title="Australian Business Number">ABN</abbr>: 63 942 912 684</li>
          <li class="cricos-code secondary">
            <abbr title="Commonwealth Register of Institutions and Courses for Overseas Students">CRICOS</abbr>
            Provider No: <a class="secondary" href="http://www.uq.edu.au/about/cricos-link" rel="external">00025B</a>
          </li>
        </ul>
      </div>
      <div class="mobile-four three columns">
        <div class="uq-emergency-contact">
          <h6>Emergency</h6>
          <ul>
            <li>Phone: <a href="tel:+61733653333">3365 3333</a></li>
          </ul>
        </div>
      </div>
    </div>

    <hr>

    <div class="row">
      <div class="mobile-four nine columns">
        <ul>
          <li><a href="http://www.uq.edu.au/terms-of-use/" rel="external">Privacy &amp; Terms of use</a></li>
          <li><a href="http://www.uq.edu.au/feedback" rel="external">Feedback</a></li>
        </ul>
      </div>
      <div class="mobile-four three columns">
        <ul>
                  <li class="last-updated secondary">Updated: 4 Oct 2016</li>
                          <li><a href="/eait_login" class="user-login secondary">Login</a></li>
                </ul>
      </div>
    </div>

  </div>
</div>