<div id="footer"  class="background-primary-color white">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <a href="https://www.elipse.uq.edu.au" target="_blank"><img class="elipse-logo" src="./img/elipse-logo.png" /></a>
      </div>
      <div class="col-md-6">
        <h4>&copy; The University of Queensland</h4>
        <ul>
          <li class="uq-enquiries">Enquiries: <a href="tel:+6173365111">+61 7 3365 1111</a></li>
          <li class="uq-contacts"><a href="http://uq.edu.au/contacts">UQ Contacts</a></li>
          <li class="uq-abn secondary"><abbr title="Australian Business Number">ABN</abbr>: 63 942 912 684</li>
          <li class="cricos-code secondary">
            <abbr title="Commonwealth Register of Institutions and Courses for Overseas Students">CRICOS</abbr>
            Provider No: <a class="secondary" href="http://www.uq.edu.au/about/cricos-link" rel="external">00025B</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
