<div id="footer"  class="background-primary-color white">
    <div class="container">
        <div class="row" style="margin-top: 20px;">
            <div class="col-md-4">
                <a href="https://www.elipse.uq.edu.au" target="_blank"><img class="elipse-logo" src="./img/elipse-logo.png" /></a>
            </div>
            <div class="col-md-8">
                <a href="www.elipse.uq.edu.au">www.elipse.uq.edu.au</a> | 
                <a href="mailto:elipse@eait.uq.edu.au">elipse@eait.uq.edu.au</a> | +61 7 3346 1301
                <h4>eLearning Innovations and Partnerships in Science and Engineering</h4>
            </div>
        </div>
        <hr/>
        <div class="row">
            <div class"col-md-8" style="margin-left: 30px">
                <span>&copy; The University of Queensland</span> | 
                <span class="uq-enquiries">Enquiries: <a href="tel:+6173365111">+61 7 3365 1111</a></span> | 
                <span class="uq-contacts"><a href="http://uq.edu.au/contacts">UQ Contacts</a></span> | 
                <span class="uq-abn secondary"><abbr title="Austraspanan Business Number">ABN</abbr>: 63 942 912 684</span> | 
                <span class="cricos-code secondary">
                    <abbr title="Commonwealth Register of Institutions and Courses for Overseas Students">CRICOS</abbr>
                    Provider No: <a class="secondary" href="http://www.uq.edu.au/about/cricos-link" rel="external">00025B</a>
                </span>
            </div>
        </div>
    </div>
</div>
