<META HTTP-EQUIV="Pragma" CONTENT="no-cache">
<META HTTP-EQUIV="Expires" CONTENT="-1">
<!---<link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/css/smartass.css" />-->
<link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/css/bootstrap.css" />
<link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/css/custom.css" />

<script src="/smartass-dev/js/jquery.min.js"></script>
<script src="/smartass-dev/js/bootstrap.min.js"></script>

<nav class="navbar navbar-default no-radius background-primary-color">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand white" href="${pageContext.request.contextPath}">
                Smart Assignments
            </a>

        </div>

        <ul class="nav navbar-nav navbar-right">
            <li><a href="index.htm" class="white">Home</a></li>
            <li><a href="repository.htm" class="white">Repository</a></li>
            <li><a href="login.htm" class="white">Log In</a></li>
            <li><a href="register.htm" class="white">Register</a></li>
            <li><a href="index.htm?mode=browse" class="white">Browse Assignments</a></li>
            <li><a href="help.htm?context=ass-new" class="white" target="_blank">Help</a></li>
            <li><a href="composer.htm" class="white background-secondary-color">Create New</a></li>
        </ul>
    </div>
</nav>
